=== kid48/pizza_site/XML/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="restaurant">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="address">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="street" type="xs:string"/>
              <xs:element name="city" type="xs:string"/>
              <xs:element name="state" type="xs:string"/>
              <xs:element name="zipcode" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="phone" type="xs:string"/>
        <xs:element name="email" type="xs:string"/>
        <xs:element name="website" type="xs:string"/>
        <xs:element name="hours" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="day" type="xs:string"/>
              <xs:element name="open" type="xs:string"/>
              <xs:element name="close" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="menu">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="category" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="item" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string"/>
                          <xs:element name="description" type="xs:string"/>
                          <xs:element name="price" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== kid48/pizza_site/XML/rest.xml
<?xml version="1.0" encoding="UTF-8"?>
<restaurant xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="schema.xsd">
    <name>Pizza Time!</name>
    <address>
        <street>123 Main St</street>
        <city>New York</city>
        <state>NY</state>
        <zipcode>10001</zipcode>
    </address>
    <phone>(555) 555-5555</phone>
    <email>info@pizzatime.com</email>
    <website>https://www.pizzatime.com</website>
    <hours>
        <day>Monday</day>
        <open>11:00am</open>
        <close>9:00pm</close>
    </hours>
    <hours>
        <day>Tuesday</day>
        <open>10:00am</open>
        <close>8:00pm</close>
    </hours>
    <hours>
        <day>Wednesday</day>
        <open>10:00am</open>
        <close>8:00pm</close>
    </hours>
    <hours>
        <day>Thursday</day>
        <open>10:00am</open>
        <close>8:00pm</close>
    </hours>
    <hours>
        <day>Friday</day>
        <open>12:00am</open>
        <close>8:00pm</close>
    </hours>
    <hours>
        <day>Saturday</day>
        <open>12:00am</open>
        <close>8:00pm</close>
    </hours>
    <hours>
        <day>Sunday</day>
        <open>12:00am</open>
        <close>8:00pm</close>
    </hours>
    <menu>
        <category name="Appetizers">
            <item>
                <name>Garlic Bread</name>
                <description>Warm, crispy bread with garlic and butter</description>
                <price>$4.99</price>
            </item>
            <item>
                <name>Caprese Salad</name>
                <description>Tomatoes, fresh mozzarella, and basil</description>
                <price>$8.99</price>
            </item>
        </category>

        <category name="Pizza">
            <item>
                <name>Pizza from halves</name>
                <description>Assemble your 35 cm pizza with two different flavors</description>
                <price>210 K훾</price>
            </item>
            <item>
                <name>Pizza from the chef</name>
                <description>Beef pastrami , sweet pepper , tomatoes , red onion , garlic , tkemali sauce , mozzarella
                    cheese , signature tomato sauce
                </description>
                <price>388 K훾</price>
            </item>

            <item>
                <name>Cheesy</name>
                <description>Mozzarella cheese , cheddar and parmesan cheese , alfredo signature sauce
                </description>
                <price>388 K훾</price>
            </item>
            <item>
                <name>Cheesy</name>
                <description>Mozzarella cheese , cheddar and parmesan cheese , alfredo signature sauce
                </description>
                <price>388 K훾</price>
            </item>

        </category>
    </menu>

</restaurant>
